# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: 
      - main
# TODO: DO ONLY WHEN TESTS PASS!
jobs:
  Deploy:
    runs-on: ubuntu-latest
    environment: dev
    permissions:
      id-token: write  # needed for AWS auth with OIDC
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::447430344185:role/github_actions_reviewcat
        aws-region: us-west-2
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        platforms: linux/arm64
        provenance: false  # needs to be false or lambda doesn't like the type of image produced
        push: true
        tags: ${{ steps.login-ecr.outputs.registry }}/reviewcat:latest
    - name: Deploy a new Lambda 
      run: |
        aws lambda update-function-code \
            --function-name reviewcat_dev \
            --image-uri ${{ steps.login-ecr.outputs.registry }}/reviewcat:latest
